
try{
    let x = 1/undefined
} catch(e){
    console.log(e.message)
}